spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://new-health-genie-db1.cwysozrbokkx.ap-northeast-2.rds.amazonaws.com:3306/health_genie
    username: ENC(t73nhff/1j7IxUmVnxqCkg==)
    password: ENC(cqOISBwQJ9FHHnb97SmW/WbwDHjl7nCP)

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:3000/login/oauth2/code/google
          kakao:
            redirect-uri: http://localhost:3000/login/oauth2/code/kakao

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ENC(B/Hj+f1ZSv5Cl1RjirBi9jgl+QNyDXJn)
      port: 6379

# hibernate logging
logging:
  level:
    p6spy: error
    org:
      springframework:
        security: warn